config/routes.rb
Rails.application.routes.draw do
 resources :sessions, only: [:create, :new, :destroy ]
  resources :users

  resources :carts

  root 'store#index'

  resources :products

  resources :line_items

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity +=1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<table style=" width: 400px; background-color: rgba(250,250,210,0.8); border-radius: 10px; border: 4px double darkorange; text-align: center; ">
<tr style="font-weight: bold; ">
  <td style="border-bottom: 4px double darkorange;"> Image </td>
  <td style="border-bottom: 4px double darkorange;"> Title </td>
  <td style="border-bottom: 4px double darkorange;"> Price </td>
  <td style="border-bottom: 4px double darkorange; width: 70px; "> Quantity </td>
  <td style="border-bottom: 4px double darkorange;  width: 100px; "> Total </td>
</tr>
<% sum = 0 %>
<% @cart.line_items.each do |item| %>
    <tr>
        <td style=" background-color: #ffffff; width: 50px;"> <%= image_tag(item.product.image :thumb) %> </td>
        <td> <%= item.product.title %> </td>
        <td> <%= number_to_currency(item.product.price) %> </td>
        <td> <%= item.quantity %> </td>
        <td> <%= sum += item.product.price * item.quantity %> </td>
    </tr>
<% end %>
</table>
<table style=" margin-top:5px;  width: 400px; background-color: lightgoldenrodyellow; border-radius: 10px; border: 4px double darkorange; text-align: center; ">
<tr>
  <td style=" text-align: right;"> G. Total = <%= number_to_currency sum %> </td>
</tr>
</table>

<%= link_to 'Back', root_path %>