config/routes.rb
Rails.application.routes.draw do
 resources :sessions, only: [:create, :new, :destroy ]
  resources :users

  resources :carts

  root 'store#index'

  resources :products

  resources :line_items

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyCart1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style=" background-color: #19384e; margin:0px; padding: 0px;">
<table style="width: 90%; margin-left:auto; margin-right: auto; box-shadow: 0px 0px 8px #2a2a2a; border-left: solid 1px #000000; border-right: solid 1px #000000;">
  <tr>
    <td style="background-color: #CCCCCC; height: 45px;">
      <ul style=" list-style: none;">
        <li style="float: left;"> <%= link_to 'Home', root_path %>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
        <li style="float: left;"> <%= link_to 'Products', products_path %></li>
        <% unless current_user.present? %>
            <li style="float: left;"> &nbsp;&nbsp;|&nbsp;&nbsp; <%= link_to 'SignIn', new_session_path %></li>
            <li style="float: left;"> &nbsp;&nbsp;|&nbsp;&nbsp; <%= link_to 'SignUp', new_user_path %></li>
        <% end %>
        <% if current_cart.present? %>
            <li style="float: left;">&nbsp;&nbsp;|&nbsp;&nbsp;<%= link_to 'Cart', cart_path(current_cart)  %></li>
        <% end %>
        <li style="width: 400px; margin-left: auto; margin-right: 20px; font-weight: bold; color:maroon; text-align: right; "> <%= notice %> <%= "Welcome: " + current_user.email if current_user   %> &nbsp;&nbsp;&nbsp; <%= link_to 'SignOut', session_path(current_user), method: :delete if current_user.present? %> </li>

      </ul>
    </td>
  </tr>
  <tr>
    <td style="background-color: #ffffff; height: 545px; padding: 20px; vertical-align: top; " >
<%= yield %>
    </td>
  </tr>
  <tr>
    <td style="background-color: #333333; height: 45px;"> </td>
  </tr>
</table>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyCart1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style=" background-color: #730E15; margin:0px; padding: 0px;">
<table style="width: 90%; margin-left:auto; margin-right: auto; box-shadow: 0px 0px 8px #2a2a2a; border-left: solid 1px #000000; border-right: solid 1px #000000;">
  <tr>
    <td style="background-color: #CCCCCC; height: 45px;">
      <ul style=" list-style: none;">
        <li style="float: left;"> <%= link_to 'Home', root_path %>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
        <li style="float: left;"> <%= link_to 'Products', products_path %></li>
        <% if current_user.present? %>
            <li style="float: left;"> &nbsp;&nbsp;|&nbsp;&nbsp; <%= link_to 'SignOut', session_path(current_user), method: :delete %></li>
        <% else %>
            <li style="float: left;"> &nbsp;&nbsp;|&nbsp;&nbsp; <%= link_to 'SignIn', new_session_path %></li>
            <li style="float: left;"> &nbsp;&nbsp;|&nbsp;&nbsp; <%= link_to 'SignUp', new_user_path %></li>
      <% end %>
        <% if current_cart.present? %>
            <li style="float: left;">&nbsp;&nbsp;|&nbsp;&nbsp;<%= link_to 'Cart', cart_path(current_cart)  %></li>
        <% end %>
        <li style="width: 400px; margin-left: auto; margin-right: 20px; font-weight: bold; color:maroon; text-align: right; "> <%= notice %> <%= "Welcome: " + current_user.email if current_user   %> </li>

      </ul>
    </td>
  </tr>
  <tr>
    <td style="background-color: #ffffff; height: 545px; padding: 20px; vertical-align: top;">
<%= yield %>
    </td>
  </tr>
  <tr>
    <td style="background-color: #333333; height: 45px;"> </td>
  </tr>
</table>
</body>
</html>